--DEPARTMENT 
INSERT INTO DEPARTMENT (DEPT_ID,NAME,UPDATED_BY ) VALUES (10,'DEVELOPMENT','BILQU');
INSERT INTO DEPARTMENT (DEPT_ID,NAME,UPDATED_BY,CREATED_TS,UPDATED_TS ) VALUES (20,'QUALITY','BILQU',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO DEPARTMENT (DEPT_ID,NAME,UPDATED_BY,CREATED_TS,UPDATED_TS ) VALUES (30,'ARCHITECTURE','BILQU',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

--EMPLOYEE
INSERT INTO EMPLOYEE (EMP_ID,NAME,AGE,DEPT_ID) VALUES (1001,'ANNA',31,10);
INSERT INTO EMPLOYEE (EMP_ID,NAME,AGE,DEPT_ID) VALUES (1002,'EVE',38,20);
INSERT INTO EMPLOYEE (EMP_ID,NAME,AGE,UPDATED_BY,DEPT_ID) VALUES (1003,'ADAM',38,'BILQU',10);
INSERT INTO EMPLOYEE (EMP_ID,NAME,AGE,UPDATED_BY,CREATED_TS,UPDATED_TS,DEPT_ID) VALUES (1004,'MIA',31,'BILQU',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,30);
